import subprocess

# List your commands here
commands = [
        
    "python fusion.py --run_id run1 --use_pruned --prune_amount 50_04percent",
    "python fusion.py --run_id run2 --use_pruned --prune_amount 50_04percent",
    "python fusion.py --run_id run3 --use_pruned --prune_amount 50_04percent",
    "python fusion.py --run_id run1 --use_pruned --prune_amount 4_00percent --use_softmax",
    "python fusion.py --run_id run2 --use_pruned --prune_amount 4_00percent --use_softmax",
    "python fusion.py --run_id run3 --use_pruned --prune_amount 4_00percent --use_softmax",
    "python fusion.py --run_id run1 --use_pruned --prune_amount 7_84percent --use_softmax",
    "python fusion.py --run_id run2 --use_pruned --prune_amount 7_84percent --use_softmax",
    "python fusion.py --run_id run3 --use_pruned --prune_amount 7_84percent --use_softmax",
    "python fusion.py --run_id run1 --use_pruned --prune_amount 11_53percent --use_softmax",
    "python fusion.py --run_id run2 --use_pruned --prune_amount 11_53percent --use_softmax",
    "python fusion.py --run_id run3 --use_pruned --prune_amount 11_53percent --use_softmax",
    "python fusion.py --run_id run1 --use_pruned --prune_amount 15_07percent --use_softmax",
    "python fusion.py --run_id run2 --use_pruned --prune_amount 15_07percent --use_softmax",
    "python fusion.py --run_id run3 --use_pruned --prune_amount 15_07percent --use_softmax",
    "python fusion.py --run_id run1 --use_pruned --prune_amount 18_46percent --use_softmax",
    "python fusion.py --run_id run2 --use_pruned --prune_amount 18_46percent --use_softmax",
    "python fusion.py --run_id run3 --use_pruned --prune_amount 18_46percent --use_softmax",
    "python fusion.py --run_id run1 --use_pruned --prune_amount 21_72percent --use_softmax",
    "python fusion.py --run_id run2 --use_pruned --prune_amount 21_72percent --use_softmax",
    "python fusion.py --run_id run3 --use_pruned --prune_amount 21_72percent --use_softmax",
    "python fusion.py --run_id run1 --use_pruned --prune_amount 24_86percent --use_softmax",
    "python fusion.py --run_id run2 --use_pruned --prune_amount 24_86percent --use_softmax",
    "python fusion.py --run_id run3 --use_pruned --prune_amount 24_86percent --use_softmax",
    "python fusion.py --run_id run1 --use_pruned --prune_amount 27_86percent --use_softmax",
    "python fusion.py --run_id run2 --use_pruned --prune_amount 27_86percent --use_softmax",
    "python fusion.py --run_id run3 --use_pruned --prune_amount 27_86percent --use_softmax",
    "python fusion.py --run_id run1 --use_pruned --prune_amount 30_75percent --use_softmax",
    "python fusion.py --run_id run2 --use_pruned --prune_amount 30_75percent --use_softmax",
    "python fusion.py --run_id run3 --use_pruned --prune_amount 30_75percent --use_softmax",
    "python fusion.py --run_id run1 --use_pruned --prune_amount 33_52percent --use_softmax",
    "python fusion.py --run_id run2 --use_pruned --prune_amount 33_52percent --use_softmax",
    "python fusion.py --run_id run3 --use_pruned --prune_amount 33_52percent --use_softmax",
    "python fusion.py --run_id run1 --use_pruned --prune_amount 36_18percent --use_softmax",
    "python fusion.py --run_id run2 --use_pruned --prune_amount 36_18percent --use_softmax",
    "python fusion.py --run_id run3 --use_pruned --prune_amount 36_18percent --use_softmax",
    "python fusion.py --run_id run1 --use_pruned --prune_amount 38_73percent --use_softmax",
    "python fusion.py --run_id run2 --use_pruned --prune_amount 38_73percent --use_softmax",
    "python fusion.py --run_id run3 --use_pruned --prune_amount 38_73percent --use_softmax",
    "python fusion.py --run_id run1 --use_pruned --prune_amount 41_18percent --use_softmax",
    "python fusion.py --run_id run2 --use_pruned --prune_amount 41_18percent --use_softmax",
    "python fusion.py --run_id run3 --use_pruned --prune_amount 41_18percent --use_softmax",
    "python fusion.py --run_id run1 --use_pruned --prune_amount 43_53percent --use_softmax",
    "python fusion.py --run_id run2 --use_pruned --prune_amount 43_53percent --use_softmax",
    "python fusion.py --run_id run3 --use_pruned --prune_amount 43_53percent --use_softmax",
    "python fusion.py --run_id run1 --use_pruned --prune_amount 45_79percent --use_softmax",
    "python fusion.py --run_id run2 --use_pruned --prune_amount 45_79percent --use_softmax",
    "python fusion.py --run_id run3 --use_pruned --prune_amount 45_79percent --use_softmax",
    "python fusion.py --run_id run1 --use_pruned --prune_amount 47_96percent --use_softmax",
    "python fusion.py --run_id run2 --use_pruned --prune_amount 47_96percent --use_softmax",
    "python fusion.py --run_id run3 --use_pruned --prune_amount 47_96percent --use_softmax",
    "python fusion.py --run_id run1 --use_pruned --prune_amount 50_04percent --use_softmax",
    "python fusion.py --run_id run2 --use_pruned --prune_amount 50_04percent --use_softmax",
    "python fusion.py --run_id run3 --use_pruned --prune_amount 50_04percent --use_softmax"
]

commands2 = [
    "python fusion.py --run_id run4",
    "python fusion.py --run_id run5",
    "python fusion.py --run_id run4 --use_softmax",
    "python fusion.py --run_id run5 --use_softmax",
    "python fusion.py --run_id run4 --use_pruned --prune_amount 4_00percent",
    "python fusion.py --run_id run5 --use_pruned --prune_amount 4_00percent",
    "python fusion.py --run_id run4 --use_pruned --prune_amount 7_84percent",
    "python fusion.py --run_id run5 --use_pruned --prune_amount 7_84percent",
    "python fusion.py --run_id run4 --use_pruned --prune_amount 11_53percent",
    "python fusion.py --run_id run5 --use_pruned --prune_amount 11_53percent",
    "python fusion.py --run_id run4 --use_pruned --prune_amount 15_07percent",
    "python fusion.py --run_id run5 --use_pruned --prune_amount 15_07percent",
    "python fusion.py --run_id run4 --use_pruned --prune_amount 18_46percent",
    "python fusion.py --run_id run5 --use_pruned --prune_amount 18_46percent",
    "python fusion.py --run_id run4 --use_pruned --prune_amount 21_72percent",
    "python fusion.py --run_id run5 --use_pruned --prune_amount 21_72percent",
    "python fusion.py --run_id run4 --use_pruned --prune_amount 24_86percent",
    "python fusion.py --run_id run5 --use_pruned --prune_amount 24_86percent",
    "python fusion.py --run_id run4 --use_pruned --prune_amount 27_86percent",
    "python fusion.py --run_id run5 --use_pruned --prune_amount 27_86percent",
    "python fusion.py --run_id run4 --use_pruned --prune_amount 30_75percent",
    "python fusion.py --run_id run5 --use_pruned --prune_amount 30_75percent",
    "python fusion.py --run_id run4 --use_pruned --prune_amount 33_52percent",
    "python fusion.py --run_id run5 --use_pruned --prune_amount 33_52percent",
    "python fusion.py --run_id run4 --use_pruned --prune_amount 36_18percent",
    "python fusion.py --run_id run5 --use_pruned --prune_amount 36_18percent",
    "python fusion.py --run_id run4 --use_pruned --prune_amount 38_73percent",
    "python fusion.py --run_id run5 --use_pruned --prune_amount 38_73percent",
    "python fusion.py --run_id run4 --use_pruned --prune_amount 41_18percent",
    "python fusion.py --run_id run5 --use_pruned --prune_amount 41_18percent",
    "python fusion.py --run_id run4 --use_pruned --prune_amount 43_53percent",
    "python fusion.py --run_id run5 --use_pruned --prune_amount 43_53percent",
    "python fusion.py --run_id run4 --use_pruned --prune_amount 45_79percent",
    "python fusion.py --run_id run5 --use_pruned --prune_amount 45_79percent",
    "python fusion.py --run_id run4 --use_pruned --prune_amount 47_96percent",
    "python fusion.py --run_id run5 --use_pruned --prune_amount 47_96percent",
    "python fusion.py --run_id run4 --use_pruned --prune_amount 50_04percent",
    "python fusion.py --run_id run5 --use_pruned --prune_amount 50_04percent",
    "python fusion.py --run_id run4 --use_pruned --prune_amount 4_00percent --use_softmax",
    "python fusion.py --run_id run5 --use_pruned --prune_amount 4_00percent --use_softmax",
    "python fusion.py --run_id run4 --use_pruned --prune_amount 7_84percent --use_softmax",
    "python fusion.py --run_id run5 --use_pruned --prune_amount 7_84percent --use_softmax",
    "python fusion.py --run_id run4 --use_pruned --prune_amount 11_53percent --use_softmax",
    "python fusion.py --run_id run5 --use_pruned --prune_amount 11_53percent --use_softmax",
    "python fusion.py --run_id run4 --use_pruned --prune_amount 15_07percent --use_softmax",
    "python fusion.py --run_id run5 --use_pruned --prune_amount 15_07percent --use_softmax",
    "python fusion.py --run_id run4 --use_pruned --prune_amount 18_46percent --use_softmax",
    "python fusion.py --run_id run5 --use_pruned --prune_amount 18_46percent --use_softmax",
    "python fusion.py --run_id run4 --use_pruned --prune_amount 21_72percent --use_softmax",
    "python fusion.py --run_id run5 --use_pruned --prune_amount 21_72percent --use_softmax",
    "python fusion.py --run_id run4 --use_pruned --prune_amount 24_86percent --use_softmax",
    "python fusion.py --run_id run5 --use_pruned --prune_amount 24_86percent --use_softmax",
    "python fusion.py --run_id run4 --use_pruned --prune_amount 27_86percent --use_softmax",
    "python fusion.py --run_id run5 --use_pruned --prune_amount 27_86percent --use_softmax",
    "python fusion.py --run_id run4 --use_pruned --prune_amount 30_75percent --use_softmax",
    "python fusion.py --run_id run5 --use_pruned --prune_amount 30_75percent --use_softmax",
    "python fusion.py --run_id run4 --use_pruned --prune_amount 33_52percent --use_softmax",
    "python fusion.py --run_id run5 --use_pruned --prune_amount 33_52percent --use_softmax",
    "python fusion.py --run_id run4 --use_pruned --prune_amount 36_18percent --use_softmax",
    "python fusion.py --run_id run5 --use_pruned --prune_amount 36_18percent --use_softmax",
    "python fusion.py --run_id run4 --use_pruned --prune_amount 38_73percent --use_softmax",
    "python fusion.py --run_id run5 --use_pruned --prune_amount 38_73percent --use_softmax",
    "python fusion.py --run_id run4 --use_pruned --prune_amount 41_18percent --use_softmax",
    "python fusion.py --run_id run5 --use_pruned --prune_amount 41_18percent --use_softmax",
    "python fusion.py --run_id run4 --use_pruned --prune_amount 43_53percent --use_softmax",
    "python fusion.py --run_id run5 --use_pruned --prune_amount 43_53percent --use_softmax",
    "python fusion.py --run_id run4 --use_pruned --prune_amount 45_79percent --use_softmax",
    "python fusion.py --run_id run5 --use_pruned --prune_amount 45_79percent --use_softmax",
    "python fusion.py --run_id run4 --use_pruned --prune_amount 47_96percent --use_softmax",
    "python fusion.py --run_id run5 --use_pruned --prune_amount 47_96percent --use_softmax",
    "python fusion.py --run_id run4 --use_pruned --prune_amount 50_04percent --use_softmax",
    "python fusion.py --run_id run5 --use_pruned --prune_amount 50_04percent --use_softmax"

]

for cmd in commands2:
    result = subprocess.run(cmd, shell=True)
    if result.returncode != 0:
        print(f"Command failed: {cmd}")
        break  # Optionally stop if a command fails